import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/lib/auth/config";
import { prisma } from "@1000mm/db";
import { renderToBuffer } from "@react-pdf/renderer";
import { TrainerRosterPdf } from "@/lib/exports/TrainerRosterPdf";
import * as XLSX from "xlsx";
import React from "react";

function fmtDate(d: Date | string) {
  return new Date(d).toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric" });
}

async function getData(trainerId: string, programId: string, topicId: string) {
  // Verify topic belongs to this trainer
  const topic = await prisma.programTopic.findFirst({
    where: { id: topicId, programId, trainerId, deletedAt: null },
    select: { id: true, title: true, program: { select: { id: true, title: true, code: true } } },
  });
  if (!topic) return null;

  // All enrolled trainees for this program
  const enrollments = await prisma.programEnrollment.findMany({
    where: { programId, deletedAt: null },
    orderBy: { enrolledAt: "asc" },
    include: {
      trainee: {
        select: {
          id: true,
          fullName: true,
          email: true,
          homeMission: { select: { code: true } },
        },
      },
    },
  });

  return { topic, enrollments };
}

export async function GET(req: NextRequest) {
  const session = await auth();
  if (!session?.user?.id) return new NextResponse("Unauthorized", { status: 401 });
  if (session.user.role !== "TRAINER") return new NextResponse("Forbidden", { status: 403 });

  const { searchParams } = new URL(req.url);
  const programId = searchParams.get("programId") ?? "";
  const topicId = searchParams.get("topicId") ?? "";
  const format = searchParams.get("format") ?? "pdf";

  if (!programId || !topicId) return new NextResponse("Missing params", { status: 400 });

  const result = await getData(session.user.id, programId, topicId);
  if (!result) return new NextResponse("Not found or access denied", { status: 403 });

  const { topic, enrollments } = result;
  const trainer = await prisma.user.findUnique({
    where: { id: session.user.id },
    select: { fullName: true },
  });

  const rows = enrollments.map((e) => ({
    fullName: e.trainee.fullName,
    email: e.trainee.email,
    missionCode: e.trainee.homeMission.code,
    enrolledAt: fmtDate(e.enrolledAt),
    attendanceConfirmed: e.attendanceConfirmed,
  }));

  const generatedAt = new Date().toLocaleString("en-GB");
  const generatedBy = trainer?.fullName ?? "Trainer";

  if (format === "xlsx") {
    const xlsxRows = rows.map((r, i) => ({
      "#": i + 1,
      "Full Name": r.fullName,
      "Email": r.email,
      "Mission": r.missionCode,
      "Enrolled": r.enrolledAt,
      "Attendance Confirmed": r.attendanceConfirmed ? "Yes" : "No",
    }));

    const wb = XLSX.utils.book_new();
    const ws = XLSX.utils.json_to_sheet(xlsxRows);
    ws["!cols"] = Object.keys(xlsxRows[0] ?? {}).map((k) => ({
      wch: Math.max(k.length, ...xlsxRows.map((r) => String(r[k as keyof typeof r] ?? "").length)) + 2,
    }));
    XLSX.utils.book_append_sheet(wb, ws, "Trainees");

    const summaryRows = [
      { Field: "Organization", Value: "1000 Missionary Movement Bangladesh" },
      { Field: "Report", Value: "Trainee Roster" },
      { Field: "Program", Value: `${topic.program.code} — ${topic.program.title}` },
      { Field: "Topic", Value: topic.title },
      { Field: "Trainer", Value: generatedBy },
      { Field: "", Value: "" },
      { Field: "Total Trainees", Value: rows.length },
      { Field: "Attendance Confirmed", Value: rows.filter((r) => r.attendanceConfirmed).length },
      { Field: "", Value: "" },
      { Field: "Generated At", Value: generatedAt },
      { Field: "Generated By", Value: generatedBy },
    ];
    const ws2 = XLSX.utils.json_to_sheet(summaryRows);
    ws2["!cols"] = [{ wch: 28 }, { wch: 40 }];
    XLSX.utils.book_append_sheet(wb, ws2, "Summary");

    const buffer = XLSX.write(wb, { type: "buffer", bookType: "xlsx" });
    return new NextResponse(new Uint8Array(buffer), {
      headers: {
        "Content-Type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "Content-Disposition": `attachment; filename="trainer-roster-${Date.now()}.xlsx"`,
      },
    });
  }

  // PDF
  const buffer = await renderToBuffer(
    React.createElement(TrainerRosterPdf, {
      programTitle: topic.program.title,
      programCode: topic.program.code,
      topicTitle: topic.title,
      trainerName: generatedBy,
      rows,
      generatedAt,
      generatedBy,
    }) as any);

  return new NextResponse(new Uint8Array(buffer), {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="trainer-roster-${Date.now()}.pdf"`,
    },
  });
}
