import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/lib/auth/config";
import { prisma } from "@1000mm/db";
import * as XLSX from "xlsx";
import {
  parseMissionariesExportFilters,
  buildMissionariesExportWhere,
  describeMissionariesFilters,
} from "@/lib/exports/missionariesQuery";

export async function GET(req: NextRequest) {
  const session = await auth();
  if (!session?.user?.id)
    return new NextResponse("Unauthorized", { status: 401 });

  const user = await prisma.user.findUnique({
    where: { id: session.user.id },
    include: { homeMission: true },
  });
  if (
    !user ||
    !["LOCAL_DIRECTOR", "MAIN_DIRECTOR", "SYSTEM_ADMIN"].includes(user.role)
  ) {
    return new NextResponse("Forbidden", { status: 403 });
  }

  const { searchParams } = new URL(req.url);
  const filters = parseMissionariesExportFilters(searchParams);

  const isLmd = user.role === "LOCAL_DIRECTOR";
  const lmdMission = isLmd
    ? await prisma.localMission.findFirst({ where: { directorId: user.id } })
    : null;
  if (isLmd) filters.mission = undefined;

  const where = buildMissionariesExportWhere(filters, {
    lmdMissionId: isLmd ? (lmdMission?.id ?? null) : null,
  });

  const deployments = await prisma.missionaryDeployment.findMany({
    where,
    orderBy: [
      { mission: { code: "asc" } },
      { status: "asc" },
      { startDate: "asc" },
    ],
    include: {
      missionary: {
        select: {
          fullName: true,
          phone: true,
          dateOfBirth: true,
          homeMission: { select: { code: true } },
        },
      },
      mission: { select: { code: true, name: true } },
      requestedBy: { select: { fullName: true } },
      reviewedBy: { select: { fullName: true } },
    },
  });

  const fmt = (d: Date | null | undefined) =>
    d ? new Date(d).toLocaleDateString("en-GB") : "";

  const rows = deployments.map((d, i) => ({
    "#": i + 1,
    "Full Name": d.missionary.fullName,
    "Home Mission": d.missionary.homeMission.code,
    Phone: d.missionary.phone ?? "",
    "Date of Birth": fmt(d.missionary.dateOfBirth),
    "Deployed To": d.mission.code,
    "Field Location": d.location ?? "",
    "Start Date": fmt(d.startDate),
    "End Date": fmt(d.endDate),
    Status: d.status,
    "Requested By": d.requestedBy.fullName,
    "Approved/Reviewed By": d.reviewedBy?.fullName ?? "",
    "Review Note": d.reviewNote ?? "",
    "Created At": fmt(d.createdAt),
  }));

  const wb = XLSX.utils.book_new();
  const ws = XLSX.utils.json_to_sheet(rows);

  const colWidths = Object.keys(rows[0] ?? {}).map((key) => ({
    wch:
      Math.max(
        key.length,
        ...rows.map((r) => String(r[key as keyof typeof r] ?? "").length),
      ) + 2,
  }));
  ws["!cols"] = colWidths;

  XLSX.utils.book_append_sheet(wb, ws, "Missionaries");

  // Summary sheet
  const statusCounts: Record<string, number> = {};
  for (const d of deployments) {
    statusCounts[d.status] = (statusCounts[d.status] ?? 0) + 1;
  }
  const filterLabel = describeMissionariesFilters(filters, {
    lmdMissionCode: isLmd ? (lmdMission?.code ?? null) : null,
  });
  const summaryRows = [
    { Summary: "Total Records", Count: deployments.length },
    { Summary: "Filters", Count: filterLabel },
    { Summary: "", Count: "" },
    ...Object.entries(statusCounts).map(([s, c]) => ({ Summary: s, Count: c })),
    { Summary: "", Count: "" },
    { Summary: "Generated At", Count: new Date().toLocaleString("en-GB") },
    { Summary: "Generated By", Count: user.fullName },
  ];
  const ws2 = XLSX.utils.json_to_sheet(summaryRows);
  ws2["!cols"] = [{ wch: 30 }, { wch: 25 }];
  XLSX.utils.book_append_sheet(wb, ws2, "Summary");

  const buffer = XLSX.write(wb, { type: "buffer", bookType: "xlsx" });

  return new NextResponse(new Uint8Array(buffer), {
    headers: {
      "Content-Type":
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      "Content-Disposition": `attachment; filename="missionaries-${Date.now()}.xlsx"`,
    },
  });
}
