services:
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mm1000

  portal:
    build: ./apps/portal
    ports:
      - "3001:3001"

  website:
    build: ./apps/website
    ports:
      - "3000:3000"
