import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/lib/auth/config";
import { prisma } from "@1000mm/db";
import * as XLSX from "xlsx";

const MONTHS = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];

export async function GET(req: NextRequest) {
  const session = await auth();
  if (!session?.user?.id) return new NextResponse("Unauthorized", { status: 401 });

  const user = await prisma.user.findUnique({
    where: { id: session.user.id },
    select: { id: true, role: true, fullName: true },
  });
  if (!user || user.role !== "LOCAL_DIRECTOR")
    return new NextResponse("Forbidden", { status: 403 });

  const mission = await prisma.localMission.findFirst({ where: { directorId: user.id } });
  if (!mission) return new NextResponse("No mission assigned", { status: 400 });

  const { searchParams } = new URL(req.url);
  const yearParam     = searchParams.get("year");
  const monthParam    = searchParams.get("month");
  const genderParam   = searchParams.get("gender");
  const districtParam = searchParams.get("district");

  const thisYear = new Date().getFullYear();
  const yearNum  = yearParam  ? parseInt(yearParam,  10) : thisYear;
  const monthNum = monthParam ? parseInt(monthParam, 10) : undefined;

  const appFilter: Record<string, unknown> = { status: "ACCEPTED" };
  if (genderParam === "MALE" || genderParam === "FEMALE") appFilter.applicantGender = genderParam;
  if (districtParam) appFilter.presentAddressDistrict = districtParam;
  const hasAppFilter = !!(genderParam || districtParam);

  let createdAtFilter: Record<string, Date> | undefined;
  if (monthNum) {
    createdAtFilter = {
      gte: new Date(yearNum, monthNum - 1, 1),
      lt:  new Date(yearNum, monthNum,     1),
    };
  }

  const [missionaries, assignments] = await Promise.all([
    prisma.user.findMany({
      where: {
        homeMissionId: mission.id,
        isMissionary: true,
        isActive: true,
        ...(hasAppFilter ? { applications: { some: appFilter } } : {}),
        ...(monthNum ? { salaryAssignments: { some: { missionId: mission.id, cycle: yearNum, createdAt: createdAtFilter } } } : {}),
      },
      orderBy: { fullName: "asc" },
      include: {
        applications: {
          where: { status: "ACCEPTED" },
          select: { applicantGender: true, presentAddressDistrict: true },
          orderBy: { createdAt: "desc" },
          take: 1,
        },
      },
    }),
    prisma.salaryAssignment.findMany({
      where: {
        missionId: mission.id,
        cycle: yearNum,
        ...(createdAtFilter ? { createdAt: createdAtFilter } : {}),
      },
    }),
  ]);

  const assignmentMap = new Map(assignments.map((a) => [a.missionaryId, a]));

  const rows = missionaries.map((m, i) => {
    const a   = assignmentMap.get(m.id);
    const app = m.applications[0];
    return {
      "#":                  i + 1,
      "Name":               m.fullName,
      "Email":              m.email,
      "Gender":             app?.applicantGender === "MALE" ? "Male" : app?.applicantGender === "FEMALE" ? "Female" : "—",
      "District":           app?.presentAddressDistrict ?? "—",
      "Cycle (Year)":       yearNum,
      "Deployment Location":a?.deploymentLocation ?? "—",
      "Amount (৳)":         a?.amount ?? 0,
      "Status":             a ? "Assigned" : "Pending",
    };
  });

  const wb = XLSX.utils.book_new();
  const ws = XLSX.utils.json_to_sheet(rows);
  const colWidths = Object.keys(rows[0] ?? {}).map((key) => ({
    wch: Math.max(key.length, ...rows.map((r) => String(r[key as keyof typeof r] ?? "").length)) + 2,
  }));
  ws["!cols"] = colWidths;
  XLSX.utils.book_append_sheet(wb, ws, "Salary List");

  const totalAssigned = missionaries.reduce((s, m) => s + (assignmentMap.get(m.id)?.amount ?? 0), 0);
  const summaryRows = [
    { Summary: "1000 Missionary Movement Bangladesh", Value: "" },
    { Summary: "Mission",        Value: mission.name },
    { Summary: "Cycle (Year)",   Value: yearNum },
    { Summary: "Month Filter",   Value: monthNum ? MONTHS[monthNum - 1] : "All" },
    { Summary: "Gender Filter",  Value: genderParam ?? "All" },
    { Summary: "District Filter",Value: districtParam ?? "All" },
    { Summary: "",               Value: "" },
    { Summary: "Total Missionaries", Value: missionaries.length },
    { Summary: "Total Assigned (৳)", Value: totalAssigned },
    { Summary: "",               Value: "" },
    { Summary: "Generated At",   Value: new Date().toLocaleString("en-GB") },
    { Summary: "Generated By",   Value: user.fullName },
  ];
  const ws2 = XLSX.utils.json_to_sheet(summaryRows);
  ws2["!cols"] = [{ wch: 30 }, { wch: 30 }];
  XLSX.utils.book_append_sheet(wb, ws2, "Summary");

  const buffer = XLSX.write(wb, { type: "buffer", bookType: "xlsx" });
  return new NextResponse(new Uint8Array(buffer), {
    headers: {
      "Content-Type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      "Content-Disposition": `attachment; filename="lmd-salary-${yearNum}.xlsx"`,
    },
  });
}
