import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/lib/auth/config";
import { prisma } from "@1000mm/db";
import { renderToBuffer } from "@react-pdf/renderer";
import { TrainerSubmissionsPdf } from "@/lib/exports/TrainerSubmissionsPdf";
import * as XLSX from "xlsx";
import React from "react";

function fmtDate(d: Date | string | null) {
  if (!d) return null;
  return new Date(d).toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric" });
}

function fmtDateTime(d: Date | string | null) {
  if (!d) return null;
  return new Date(d).toLocaleString("en-GB", { day: "numeric", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit" });
}

export async function GET(req: NextRequest) {
  const session = await auth();
  if (!session?.user?.id) return new NextResponse("Unauthorized", { status: 401 });
  if (session.user.role !== "TRAINER") return new NextResponse("Forbidden", { status: 403 });

  const { searchParams } = new URL(req.url);
  const assignmentId = searchParams.get("assignmentId") ?? "";
  const format = searchParams.get("format") ?? "pdf";

  if (!assignmentId) return new NextResponse("Missing assignmentId", { status: 400 });

  // Load assignment — must be created by this trainer
  const assignment = await prisma.assignment.findFirst({
    where: { id: assignmentId, createdById: session.user.id, deletedAt: null },
    include: {
      program: { select: { id: true, title: true, code: true } },
      topic: { select: { id: true, title: true } },
      submissions: {
        include: {
          trainee: { select: { fullName: true, homeMission: { select: { code: true } } } },
        },
        orderBy: { submittedAt: "asc" },
      },
    },
  });
  if (!assignment) return new NextResponse("Not found or access denied", { status: 403 });

  const trainer = await prisma.user.findUnique({
    where: { id: session.user.id },
    select: { fullName: true },
  });

  // All enrolled trainees for full picture (including non-submitted)
  const enrollments = await prisma.programEnrollment.findMany({
    where: { programId: assignment.programId, deletedAt: null },
    orderBy: { enrolledAt: "asc" },
    include: {
      trainee: { select: { id: true, fullName: true, homeMission: { select: { code: true } } } },
    },
  });

  const submissionMap = new Map(
    assignment.submissions.map((s) => [s.traineeId, s])
  );

  const rows = enrollments.map((e) => {
    const sub = submissionMap.get(e.traineeId);
    return {
      fullName: e.trainee.fullName,
      missionCode: e.trainee.homeMission?.code ?? "—",
      submitted: !!sub,
      submittedAt: sub ? fmtDateTime(sub.submittedAt) : null,
      notes: sub?.notes ?? null,
      hasFile: !!sub?.fileStorageKey,
      feedback: sub?.feedback ?? null,
      feedbackAt: sub?.feedbackAt ? fmtDate(sub.feedbackAt) : null,
    };
  });

  const generatedAt = new Date().toLocaleString("en-GB");
  const generatedBy = trainer?.fullName ?? "Trainer";
  const topicTitle = assignment.topic?.title ?? "General";

  if (format === "xlsx") {
    const xlsxRows = rows.map((r, i) => ({
      "#": i + 1,
      "Trainee": r.fullName,
      "Mission": r.missionCode,
      "Status": r.submitted ? (r.hasFile ? "Submitted (file)" : "Submitted") : "Pending",
      "Submitted At": r.submittedAt ?? "",
      "Response Notes": r.notes ?? (r.hasFile ? "[File attached]" : ""),
      "Feedback": r.feedback ?? "",
      "Feedback Date": r.feedbackAt ?? "",
    }));

    const wb = XLSX.utils.book_new();
    const ws = XLSX.utils.json_to_sheet(xlsxRows);
    ws["!cols"] = Object.keys(xlsxRows[0] ?? {}).map((k) => ({
      wch: Math.max(k.length, ...xlsxRows.map((r) => String(r[k as keyof typeof r] ?? "").length)) + 2,
    }));
    XLSX.utils.book_append_sheet(wb, ws, "Submissions");

    const submitted = rows.filter((r) => r.submitted).length;
    const feedbackGiven = rows.filter((r) => r.feedback).length;
    const summaryRows = [
      { Field: "Organization", Value: "1000 Missionary Movement Bangladesh" },
      { Field: "Report", Value: "Assignment Submissions" },
      { Field: "Program", Value: `${assignment.program.code} — ${assignment.program.title}` },
      { Field: "Topic", Value: topicTitle },
      { Field: "Assignment", Value: assignment.title },
      { Field: "Due Date", Value: fmtDate(assignment.dueDate) ?? "No due date" },
      { Field: "Trainer", Value: generatedBy },
      { Field: "", Value: "" },
      { Field: "Total Enrolled", Value: rows.length },
      { Field: "Submitted", Value: submitted },
      { Field: "Pending", Value: rows.length - submitted },
      { Field: "Feedback Given", Value: feedbackGiven },
      { Field: "", Value: "" },
      { Field: "Generated At", Value: generatedAt },
      { Field: "Generated By", Value: generatedBy },
    ];
    const ws2 = XLSX.utils.json_to_sheet(summaryRows);
    ws2["!cols"] = [{ wch: 28 }, { wch: 50 }];
    XLSX.utils.book_append_sheet(wb, ws2, "Summary");

    const buffer = XLSX.write(wb, { type: "buffer", bookType: "xlsx" });
    return new NextResponse(new Uint8Array(buffer), {
      headers: {
        "Content-Type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "Content-Disposition": `attachment; filename="assignment-submissions-${Date.now()}.xlsx"`,
      },
    });
  }

  // PDF
  const buffer = await renderToBuffer(
    React.createElement(TrainerSubmissionsPdf, {
      programTitle: assignment.program.title,
      programCode: assignment.program.code,
      topicTitle,
      assignmentTitle: assignment.title,
      dueDate: fmtDate(assignment.dueDate),
      trainerName: generatedBy,
      rows,
      generatedAt,
      generatedBy,
    }) as any
  );

  return new NextResponse(new Uint8Array(buffer), {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="assignment-submissions-${Date.now()}.pdf"`,
    },
  });
}
