import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/lib/auth/config";
import { prisma } from "@1000mm/db";
import * as XLSX from "xlsx";

const MONTHS = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];

export async function GET(req: NextRequest) {
  const session = await auth();
  if (!session?.user?.id)
    return new NextResponse("Unauthorized", { status: 401 });

  const user = await prisma.user.findUnique({
    where: { id: session.user.id },
    select: { id: true, role: true, fullName: true },
  });
  if (!user || !["SYSTEM_ADMIN", "MAIN_DIRECTOR"].includes(user.role)) {
    return new NextResponse("Forbidden", { status: 403 });
  }

  const { searchParams } = new URL(req.url);
  const missionCode = searchParams.get("mission") ?? undefined;
  const yearParam = searchParams.get("year");
  const monthParam = searchParams.get("month");
  const statusParam = searchParams.get("status") ?? undefined;
  const programParam = searchParams.get("program") ?? undefined;

  const yearNum = yearParam ? parseInt(yearParam, 10) : undefined;
  const monthNum = monthParam ? parseInt(monthParam, 10) : undefined;

  const missions = await prisma.localMission.findMany({
    where: { deletedAt: null },
    select: { id: true, code: true },
  });
  const missionId = missionCode ? missions.find((m) => m.code === missionCode)?.id : undefined;

  const requests = await prisma.salaryRequest.findMany({
    where: {
      ...(missionId ? { missionId } : {}),
      ...(yearNum ? { year: yearNum } : {}),
      ...(monthNum ? { month: monthNum } : {}),
      ...(statusParam ? { status: statusParam as any } : {}),
      ...(programParam
        ? {
            missionary: {
              enrollmentsAsTrainee: {
                some: { programId: programParam, deletedAt: null },
              },
            },
          }
        : {}),
    },
    orderBy: [{ year: "desc" }, { month: "desc" }, { createdAt: "desc" }],
    include: {
      missionary: { select: { fullName: true, email: true } },
      mission: { select: { code: true, name: true } },
      reviewedBy: { select: { fullName: true } },
    },
  });

  const rows = requests.map((r, i) => ({
    "#": i + 1,
    "Missionary": r.missionary.fullName,
    "Email": r.missionary.email,
    "Mission": r.mission.code,
    "Month": MONTHS[r.month - 1],
    "Year": r.year,
    "Amount (৳)": r.amount,
    "Status": r.status,
    "Notes": r.notes ?? "",
    "Reviewed By": r.reviewedBy?.fullName ?? "",
  }));

  const wb = XLSX.utils.book_new();
  const ws = XLSX.utils.json_to_sheet(rows);

  const colWidths = Object.keys(rows[0] ?? {}).map((key) => ({
    wch: Math.max(key.length, ...rows.map((r) => String(r[key as keyof typeof r] ?? "").length)) + 2,
  }));
  ws["!cols"] = colWidths;

  XLSX.utils.book_append_sheet(wb, ws, "Salary Requests");

  const approvedTotal = requests.filter((r) => r.status === "APPROVED").reduce((s, r) => s + r.amount, 0);
  const summaryRows = [
    { Summary: "1000 Missionary Movement Bangladesh", Value: "" },
    { Summary: "Report", Value: "Salary Requests" },
    { Summary: "Mission Filter", Value: missionCode ?? "All" },
    { Summary: "Year Filter", Value: yearNum ? String(yearNum) : "All" },
    { Summary: "Month Filter", Value: monthNum ? MONTHS[monthNum - 1] : "All" },
    { Summary: "Status Filter", Value: statusParam ?? "All" },
    { Summary: "", Value: "" },
    { Summary: "Total Requests", Value: requests.length },
    { Summary: "Approved Total (৳)", Value: approvedTotal },
    { Summary: "", Value: "" },
    { Summary: "Generated At", Value: new Date().toLocaleString("en-GB") },
    { Summary: "Generated By", Value: user.fullName },
  ];
  const ws2 = XLSX.utils.json_to_sheet(summaryRows);
  ws2["!cols"] = [{ wch: 30 }, { wch: 30 }];
  XLSX.utils.book_append_sheet(wb, ws2, "Summary");

  const buffer = XLSX.write(wb, { type: "buffer", bookType: "xlsx" });

  return new NextResponse(new Uint8Array(buffer), {
    headers: {
      "Content-Type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      "Content-Disposition": `attachment; filename="salary-requests-${Date.now()}.xlsx"`,
    },
  });
}
