import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: { fontFamily: "Helvetica", fontSize: 8, padding: 28, backgroundColor: "#fff" },
  title: { fontSize: 13, fontFamily: "Helvetica-Bold", color: "#1a5276" },
  subtitle: { fontSize: 8, color: "#666", marginTop: 2, marginBottom: 10 },
  headRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#1a5276",
    paddingBottom: 3,
    marginBottom: 2,
  },
  row: {
    flexDirection: "row",
    borderBottomWidth: 0.5,
    borderBottomColor: "#eee",
    paddingVertical: 3,
  },
  th: { fontFamily: "Helvetica-Bold", color: "#1a5276", fontSize: 7.5 },
  td: { color: "#222", fontSize: 7.5 },
  footer: { position: "absolute", bottom: 14, left: 28, right: 28, flexDirection: "row", justifyContent: "space-between" },
  footerText: { fontSize: 6.5, color: "#aaa" },
});

const COLS = [
  { key: "ref", label: "Reference", width: "17%" },
  { key: "name", label: "Missionary", width: "18%" },
  { key: "mission", label: "Mission", width: "8%" },
  { key: "study", label: "Planning to Study", width: "20%" },
  { key: "status", label: "Status", width: "16%" },
  { key: "submitted", label: "Submitted", width: "11%" },
  { key: "amount", label: "Funded", width: "10%" },
] as const;

export type ScholarshipPdfRow = Record<(typeof COLS)[number]["key"], string>;

export function ScholarshipListPdf({
  rows,
  scopeLabel,
  generatedBy,
  generatedAt,
  totalFunded,
}: {
  rows: ScholarshipPdfRow[];
  scopeLabel: string;
  generatedBy: string;
  generatedAt: string;
  totalFunded: string;
}) {
  return (
    <Document>
      <Page size="A4" orientation="landscape" style={styles.page}>
        <Text style={styles.title}>Scholarship Applications</Text>
        <Text style={styles.subtitle}>
          {scopeLabel} · {rows.length} application{rows.length === 1 ? "" : "s"}
          {totalFunded ? ` · Total funded ${totalFunded}` : ""}
        </Text>

        <View style={styles.headRow}>
          {COLS.map((c) => (
            <Text key={c.key} style={[styles.th, { width: c.width }]}>
              {c.label}
            </Text>
          ))}
        </View>

        {rows.map((r, i) => (
          <View key={i} style={styles.row} wrap={false}>
            {COLS.map((c) => (
              <Text key={c.key} style={[styles.td, { width: c.width }]}>
                {r[c.key] || "—"}
              </Text>
            ))}
          </View>
        ))}

        <View style={styles.footer} fixed>
          <Text style={styles.footerText}>
            Generated by {generatedBy} · {generatedAt}
          </Text>
          <Text
            style={styles.footerText}
            render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`}
          />
        </View>
      </Page>
    </Document>
  );
}
