import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/lib/auth/config";
import { prisma } from "@1000mm/db";
import * as XLSX from "xlsx";

const MONTHS = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];

export async function GET(req: NextRequest) {
  const session = await auth();
  if (!session?.user?.id)
    return new NextResponse("Unauthorized", { status: 401 });

  const user = await prisma.user.findUnique({
    where: { id: session.user.id },
    select: { id: true, role: true, fullName: true },
  });
  if (!user || !["SYSTEM_ADMIN", "MAIN_DIRECTOR", "SECRETARY", "ASSOCIATE_DIRECTOR"].includes(user.role))
    return new NextResponse("Forbidden", { status: 403 });

  const { searchParams } = new URL(req.url);
  const missionCode = searchParams.get("mission") ?? undefined;
  const yearParam   = searchParams.get("year");
  const monthParam  = searchParams.get("month");

  const yearNum  = yearParam  ? parseInt(yearParam,  10) : undefined;
  const monthNum = monthParam ? parseInt(monthParam, 10) : undefined;

  const reports = await prisma.fieldReport.findMany({
    where: {
      ...(missionCode ? { trainee: { homeMission: { code: missionCode } } } : {}),
      ...(yearNum     ? { reportYear: yearNum }   : {}),
      ...(monthNum    ? { reportMonth: monthNum } : {}),
    },
    orderBy: [{ reportYear: "desc" }, { reportMonth: "desc" }, { submittedAt: "desc" }],
    include: {
      trainee: { select: { fullName: true, homeMission: { select: { code: true } } } },
      program: { select: { code: true } },
    },
  });

  const rows = reports.map((r, i) => ({
    "#":                    i + 1,
    "Missionary":           r.trainee.fullName,
    "Mission":              r.trainee.homeMission?.code ?? "—",
    "Program":              r.program.code,
    "Month":                MONTHS[r.reportMonth - 1],
    "Year":                 r.reportYear,
    "Total Activities":     r.totalActivities,
    "Days of Work":         r.daysOfWork,
    "Hours of Work":        r.hoursOfWork,
    "Non-SDA Home Visits":  r.nonSdaHomeVisits,
    "Bible Studies":        r.bibleStudiesConducted,
    "Medical Visits":       r.medicalVisits,
    "Worship Sessions":     r.worshipSessionsTaken,
    "New Groups":           r.newGroupsMade,
    "Baptism Candidates":   r.baptismCandidatesPrepared,
    "Baptisms":             r.numberOfBaptisms,
    "People Reached":       r.peopleReached ?? 0,
    "Submitted At":         new Date(r.submittedAt).toLocaleDateString("en-GB"),
  }));

  const wb = XLSX.utils.book_new();
  const ws = XLSX.utils.json_to_sheet(rows);
  const colWidths = Object.keys(rows[0] ?? {}).map((key) => ({
    wch: Math.max(key.length, ...rows.map((r) => String(r[key as keyof typeof r] ?? "").length)) + 2,
  }));
  ws["!cols"] = colWidths;
  XLSX.utils.book_append_sheet(wb, ws, "Field Reports");

  // Summary sheet
  const totalBaptisms   = reports.reduce((s, r) => s + r.numberOfBaptisms, 0);
  const totalActivities = reports.reduce((s, r) => s + r.totalActivities,  0);
  const totalVisits     = reports.reduce((s, r) => s + r.nonSdaHomeVisits, 0);
  const totalReached    = reports.reduce((s, r) => s + (r.peopleReached ?? 0), 0);

  const summaryRows = [
    { Summary: "1000 Missionary Movement Bangladesh", Value: "" },
    { Summary: "Report",          Value: "Field Reports" },
    { Summary: "Mission Filter",  Value: missionCode ?? "All" },
    { Summary: "Year Filter",     Value: yearNum  ? String(yearNum)            : "All" },
    { Summary: "Month Filter",    Value: monthNum ? MONTHS[monthNum - 1]       : "All" },
    { Summary: "",                Value: "" },
    { Summary: "Total Reports",   Value: reports.length },
    { Summary: "Total Activities",Value: totalActivities },
    { Summary: "Total Baptisms",  Value: totalBaptisms },
    { Summary: "Total Visits",    Value: totalVisits },
    { Summary: "Total Reached",   Value: totalReached },
    { Summary: "",                Value: "" },
    { Summary: "Generated At",    Value: new Date().toLocaleString("en-GB") },
    { Summary: "Generated By",    Value: user.fullName },
  ];
  const ws2 = XLSX.utils.json_to_sheet(summaryRows);
  ws2["!cols"] = [{ wch: 30 }, { wch: 30 }];
  XLSX.utils.book_append_sheet(wb, ws2, "Summary");

  const buffer = XLSX.write(wb, { type: "buffer", bookType: "xlsx" });

  return new NextResponse(new Uint8Array(buffer), {
    headers: {
      "Content-Type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      "Content-Disposition": `attachment; filename="field-reports-${Date.now()}.xlsx"`,
    },
  });
}
