import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/lib/auth/config";
import { prisma } from "@1000mm/db";
import * as XLSX from "xlsx";
import { isSettingEnabled, SETTINGS } from "@/lib/settings";

export async function GET(req: NextRequest) {
  const session = await auth();
  if (!session?.user?.id)
    return new NextResponse("Unauthorized", { status: 401 });

  const user = await prisma.user.findUnique({
    where: { id: session.user.id },
    include: { homeMission: true },
  });
  if (
    !user ||
    !["LOCAL_DIRECTOR", "MAIN_DIRECTOR", "SYSTEM_ADMIN"].includes(user.role)
  ) {
    return new NextResponse("Forbidden", { status: 403 });
  }
  if (user.role === "MAIN_DIRECTOR") {
    const allowed = await isSettingEnabled(SETTINGS.UD_CAN_EXPORT_APPLICANTS);
    if (!allowed) return new NextResponse("Not permitted.", { status: 403 });
  }

  const { searchParams } = new URL(req.url);
  const programId = searchParams.get("programId") ?? undefined;
  const status = searchParams.get("status") ?? undefined;

  const isLmd = user.role === "LOCAL_DIRECTOR";
  const lmdMission = isLmd
    ? await prisma.localMission.findFirst({ where: { directorId: user.id } })
    : null;

  const applications = await prisma.application.findMany({
    where: {
      deletedAt: null,
      status: { not: "DRAFT" },
      ...(isLmd && lmdMission ? { submittedFromMissionId: lmdMission.id } : {}),
      ...(programId ? { window: { programId } } : {}),
      ...(status ? { status: status as any } : {}),
    },
    orderBy: [
      { submittedFromMission: { code: "asc" } },
      { referenceNumber: "asc" },
    ],
    include: {
      applicant: { select: { email: true } },
      submittedFromMission: { select: { code: true, name: true } },
      window: {
        include: { program: { select: { code: true, title: true } } },
      },
      lmdReviewer: { select: { fullName: true } },
      directorReviewer: { select: { fullName: true } },
    },
  });

  // Build rows
  const rows = applications.map((a, i) => ({
    "#": i + 1,
    "Reference No.": a.referenceNumber ?? "",
    "Full Name": a.applicantFullName,
    Gender: a.applicantGender,
    "Date of Birth": a.applicantDateOfBirth
      ? new Date(a.applicantDateOfBirth).toLocaleDateString("en-GB")
      : "",
    Age: a.applicantAge,
    Email: a.applicant.email,
    "Mobile No.": a.applicantMobileNo ?? "",
    Mission: a.submittedFromMission.code,
    District: a.presentAddressDistrict ?? "",
    Upazila: a.presentAddressUpazila ?? "",
    Church: a.applicantChurchName ?? "",
    "Blood Type": a.applicantBloodType ?? "",
    "Marital Status": a.applicantMaritalStatus ?? "",
    Denomination: a.applicantDenomination ?? "",
    Program: a.window.program.code,
    "Program Title": a.window.program.title,
    Status: a.status.replace(/_/g, " "),
    "Submitted At": a.submittedAt
      ? new Date(a.submittedAt).toLocaleDateString("en-GB")
      : "",
    "LMD Reviewer": a.lmdReviewer?.fullName ?? "",
    "Director Reviewer": a.directorReviewer?.fullName ?? "",
  }));

  // Create workbook
  const wb = XLSX.utils.book_new();
  const ws = XLSX.utils.json_to_sheet(rows);

  // Auto column widths
  const colWidths = Object.keys(rows[0] ?? {}).map((key) => ({
    wch:
      Math.max(
        key.length,
        ...rows.map((r) => String(r[key as keyof typeof r] ?? "").length),
      ) + 2,
  }));
  ws["!cols"] = colWidths;

  XLSX.utils.book_append_sheet(wb, ws, "Applicants");

  // Summary sheet
  const statusCounts: Record<string, number> = {};
  for (const a of applications) {
    statusCounts[a.status] = (statusCounts[a.status] ?? 0) + 1;
  }
  const summaryRows = [
    { Summary: "Total Applicants", Count: applications.length },
    { Summary: "", Count: "" },
    ...Object.entries(statusCounts).map(([s, c]) => ({
      Summary: s.replace(/_/g, " "),
      Count: c,
    })),
    { Summary: "", Count: "" },
    { Summary: "Generated At", Count: new Date().toLocaleString("en-GB") },
    { Summary: "Generated By", Count: user.fullName },
  ];
  const ws2 = XLSX.utils.json_to_sheet(summaryRows);
  ws2["!cols"] = [{ wch: 30 }, { wch: 20 }];
  XLSX.utils.book_append_sheet(wb, ws2, "Summary");

  const buffer = XLSX.write(wb, { type: "buffer", bookType: "xlsx" });

  return new NextResponse(new Uint8Array(buffer), {
    headers: {
      "Content-Type":
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      "Content-Disposition": `attachment; filename="applicants-${Date.now()}.xlsx"`,
    },
  });
}
